updated version of  fluent-plugin-kubernetes_metadata_filter in order to fix docker build
source: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/184

error log (of failed build):
+ gem install fluent-plugin-kubernetes_metadata_filter -v 2.1.2
Successfully installed public_suffix-4.0.2
Successfully installed addressable-2.7.0
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
	activesupport requires Ruby version >= 2.5.0.